# Generated by Django 5.1.4 on 2026-06-30 18:28

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_participant', models.IntegerField(default=10000)),
                ('public', models.BooleanField(blank=True, null=True)),
                ('registration_required', models.BooleanField(default=False)),
                ('invitation_required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'event_types',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(blank=True, null=True)),
                ('can_show_on_homepage', models.BooleanField(default=True)),
                ('can_show_on_archive', models.BooleanField(default=True)),
                ('accepting_registration', models.BooleanField(default=True)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('registration_start_time', models.DateTimeField(blank=True, null=True)),
                ('registration_end_time', models.DateTimeField(blank=True, null=True)),
                ('registration_instructions', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('ready_for_announcement', models.BooleanField(default=False)),
                ('announced_at', models.DateTimeField(blank=True, null=True)),
                ('ready_for_notifications', models.BooleanField(default=False)),
                ('notifications_sent_at', models.DateTimeField(blank=True, null=True)),
                ('ready_for_reminders', models.BooleanField(blank=True, null=True)),
                ('calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('notification_state', models.CharField(blank=True, choices=[('Init', 'Init'), ('InitialNotifications', 'Initial Notifications'), ('Reminder1', 'Reminder 1'), ('Reminder2', 'Reminder 2'), ('PresentationUpdate', 'Presentation Update'), ('Finished', 'Finished')], default='Init', max_length=255)),
                ('max_registration', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='chapters.chapter')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventtype')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('session_type', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('need_projector', models.BooleanField(default=False)),
                ('need_microphone', models.BooleanField(default=False)),
                ('need_whiteboard', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('presentation_url', models.URLField(blank=True, max_length=255)),
                ('placeholder', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sessions/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sessions', to='events.event')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_sessions',
            },
        ),
        migrations.CreateModel(
            name='EventSessionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_body', models.TextField()),
                ('event_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.eventsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_session_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('map_url', models.URLField(blank=True, max_length=255)),
                ('map_embedd_code', models.TextField(blank=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=255)),
                ('contact_mobile', models.CharField(blank=True, max_length=255)),
                ('contact_notes', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='chapters.chapter')),
            ],
            options={
                'db_table': 'venues',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.venue'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('state', models.CharField(blank=True, choices=[('Provisional', 'Provisional'), ('Confirmed', 'Confirmed'), ('Not Attending', 'Not Attending'), ('Absent', 'Absent')], max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_registrations',
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_user_per_event_registration')],
            },
        ),
    ]
