# Generated by Django 5.1.4 on 2026-07-07 17:31

import secrets

from django.db import migrations, models


def backfill_check_in_codes(apps, schema_editor):
    """Codes are minted in save() for new registrations; existing rows
    need them here so QR passes work for already-registered members."""
    EventRegistration = apps.get_model("events", "EventRegistration")
    for registration in EventRegistration.objects.filter(check_in_code__isnull=True).iterator():
        registration.check_in_code = secrets.token_urlsafe(16)
        registration.save(update_fields=["check_in_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_deleted_at_eventsession_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_absent_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_absent_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='check_in_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='check_in_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
            migrations.RunPython(backfill_check_in_codes, migrations.RunPython.noop),
    ]
