# Generated by Django 5.1.4 on 2026-07-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_auto_absent_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellation_deadline_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='custom_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='review_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='state',
            field=models.CharField(blank=True, choices=[('Provisional', 'Provisional'), ('Confirmed', 'Confirmed'), ('Not Attending', 'Not Attending'), ('Absent', 'Absent'), ('Waitlisted', 'Waitlisted')], max_length=255),
        ),
    ]
