# Generated by Django 5.1.4 on 2026-07-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_cancellation_deadline_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cancellation_deadline_hours',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
