# Generated by Django 5.1.4 on 2026-07-07 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_cancellation_deadline_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsession',
            name='co_speakers',
            field=models.ManyToManyField(blank=True, related_name='co_speaker_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='speaker_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
