# Generated by Django 5.1.4 on 2026-07-07 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coc_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coc_acknowledgements',
                'constraints': [models.UniqueConstraint(fields=('user', 'version'), name='one_ack_per_version')],
            },
        ),
    ]
