# Generated by Django 5.1.4 on 2026-06-30 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('chapter_email', models.EmailField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chapters/')),
                ('twitter_handle', models.CharField(blank=True, max_length=255)),
                ('facebook_profile', models.CharField(blank=True, max_length=255)),
                ('linkedin_profile', models.CharField(blank=True, max_length=255)),
                ('slideshare_profile', models.CharField(blank=True, max_length=255)),
                ('github_profile', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'chapters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChapterLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_leads', to='chapters.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chapter_leads',
                'constraints': [models.UniqueConstraint(fields=('user', 'chapter'), name='unique_user_per_chapter')],
            },
        ),
    ]
