# Generated by Django 5.1.4 on 2026-07-07 15:58

from django.db import migrations, models
from django.utils.text import slugify


def backfill_subdomains(apps, schema_editor):
    """Chapter.save() fills subdomain for new rows; existing rows need it
    set here or their sites 404 until someone re-saves them in admin."""
    Chapter = apps.get_model("chapters", "Chapter")
    for chapter in Chapter.objects.filter(subdomain__isnull=True):
        chapter.subdomain = slugify(chapter.name)
        chapter.save(update_fields=["subdomain"])


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subdomain',
            field=models.SlugField(blank=True, max_length=63, null=True, unique=True),
        ),
        migrations.RunPython(backfill_subdomains, migrations.RunPython.noop),
    ]
