# Generated by Django 5.1.4 on 2026-06-30 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_topic', models.CharField(max_length=255)),
                ('session_description', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_proposals', to='chapters.chapter')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_proposals', to='events.eventtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_proposals',
            },
        ),
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_topic', models.CharField(max_length=255)),
                ('session_description', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to='chapters.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_requests',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('Self', 'Self'), ('null', 'null')], default='Self', max_length=255)),
                ('achievement_type', models.CharField(choices=[('Bug Discovery', 'Bug Discovery'), ('Bug Bounty', 'Bug Bounty'), ('Open Source', 'Open Source'), ('Community Support', 'Community Support')], max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_achievements',
                'constraints': [models.UniqueConstraint(fields=('user', 'reference'), name='unique_reference_per_user')],
            },
        ),
    ]
