# Generated by Django 5.1.4 on 2026-07-07 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0002_chapter_custom_domain_chapter_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('referrer_domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=64)),
                ('utm_medium', models.CharField(blank=True, max_length=64)),
                ('utm_campaign', models.CharField(blank=True, max_length=64)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to='chapters.chapter')),
            ],
            options={
                'db_table': 'page_visits',
            },
        ),
    ]
