# Generated by Django 5.1.4 on 2026-06-30 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAutomaticNotificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('Announcement', 'Announcement'), ('SpeakerNotification', 'Speaker Notification'), ('EventReminder', 'Event Reminder'), ('SpeakerReminder', 'Speaker Reminder'), ('AdminOnCreate', 'Admin On Create'), ('PresentationUpdateReminder', 'Presentation Update Reminder')], max_length=255)),
                ('executed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_notification_tasks', to='events.event')),
            ],
            options={
                'db_table': 'event_automatic_notification_tasks',
            },
        ),
        migrations.CreateModel(
            name='EventMailerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('send_to_selected_only', models.BooleanField(default=False)),
                ('ready_for_delivery', models.BooleanField(default=False)),
                ('executed', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('registration_state', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailer_tasks', to='events.event')),
            ],
            options={
                'db_table': 'event_mailer_tasks',
            },
        ),
    ]
