# Generated by Django 5.1.4 on 2026-07-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventautomaticnotificationtask',
            name='mode',
            field=models.CharField(choices=[('Announcement', 'Announcement'), ('SpeakerNotification', 'Speaker Notification'), ('EventReminder', 'Event Reminder'), ('EventReminderFinal', 'Event Reminder Final'), ('SpeakerReminder', 'Speaker Reminder'), ('AdminOnCreate', 'Admin On Create'), ('PresentationUpdateReminder', 'Presentation Update Reminder')], max_length=255),
        ),
    ]
